### ISSUE TITLE
"When I run python main.py --phase train, the following error occurs."

### ISSUE THREAD

**Issue by jiangnan415** [wsxtyrdd/NTSCC_JSAC22#7]
Traceback (most recent call last):
  File "/home/jn/SC_work/NTSCC_JSAC22-master/main.py", line 175, in <module>
    main(sys.argv[1:])
  File "/home/jn/SC_work/NTSCC_JSAC22-master/main.py", line 163, in main
    loss = test(net, test_loader, logger)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/main.py", line 25, in test
    mse_loss_ntc, bpp_y, bpp_z, mse_loss_ntscc, cbr_y, x_hat_ntc, x_hat_ntscc = net(input_image)
  File "/home/jn/miniconda3/envs/ntscc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/net/NTSCC_Hyperior.py", line 119, in forward
    self.forward_NTC(input_image, require_probs=True)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/net/NTSCC_Hyperior.py", line 152, in forward_NTC
    return super(NTSCC_Hyperprior, self).forward(input_image, **kwargs)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/net/NTSCC_Hyperior.py", line 53, in forward
    y = self.ga(input_image)
  File "/home/jn/miniconda3/envs/ntscc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/layer/analysis_transform.py", line 98, in forward
    x = layer(x)
  File "/home/jn/miniconda3/envs/ntscc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/layer/analysis_transform.py", line 35, in forward
    x = self.downsample(x)
  File "/home/jn/miniconda3/envs/ntscc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jn/SC_work/NTSCC_JSAC22-master/layer/layers.py", line 363, in forward
    assert H % 2 == 0 and W % 2 == 0, f"x size ({H}*{W}) are not even."
AssertionError: x size (681*1024) are not even.
<img width="759" alt="image" src="https://github.com/wsxtyrdd/NTSCC_JSAC22/assets/167986607/3c8ba375-f8d8-4a01-98ec-285ccfc9e264">

**Comment by wsxtyrdd** [comment]
Please make sure the image size in your training dataset is the multipy of 64.  If you need to train NTSCC in tiny images, e.g., CIFAR10, please change the the downsampling factor of analysis/synthesis transform.
